### PR TITLE
feat/postgres

### PR DESCRIPTION
**Pull request by MurphyMarkW**
This PR is to just get things rolling w/ introducing postgres / other databases to the mix w.r.t metrics logging and whatnot. This PR should simply be a refactoring of the existing codebase such that it points to postgres without any modification outside of database handling code.

**NOTE** This should **not** be merged in until there is at least a basic travis test.

@LabAdvComp/bioinformatics

### CODE REVIEW

**Comment by MurphyMarkW** [comment]
Will be removing initial travis commits if #2 is merged.

**Comment by MurphyMarkW** [comment]
@LabAdvComp/bioinformatics Since I'm not super familiar yet with all of the different ways in which the database is going to be used, could someone try a test run w/ their pipeline using this branch for the `cdis_pipe_utils` package? You'll need to add `username` and `password` keyword arguments wherever `setup_db` is called, but should otherwise "just work" - sans anything breaking because the sqlite database is not actually present.

**Comment by MurphyMarkW** [comment]
@LabAdvComp/bioinformatics did anyone by chance have time to test this? Should be a rather minor change.

**Comment by jeremiahsavage** [comment]
This code works when I include this branch to handle parameter substitution (sqlite was forgiving in allowing double quotes).
https://github.com/LabAdvComp/cdis_pipe_utils/tree/feat/param_subst

Tested with https://github.com/LabAdvComp/cdis_pipe_utils/tree/feat/param_subst

**Pull request merged**
