### PR TITLE
separates parsing and formatting of timing info

### PR DESCRIPTION
**Pull request by MurphyMarkW**
This PR separates the parsing and formatting of timing information as produced by the GNU time utility.

@LabAdvComp/bioinformatics thoughts?

### CODE REVIEW

**Comment by stutiagrawal** [comment]
Integrated these changes with the SomaticSniper Variant Calling pipeline
and tested one dataset. It exited with no errors. Used this for running the
command and then parsing out the metrics, and then updated the metrics
dictionary directly into postgres.

On 22 January 2016 at 14:53, Mark Murphy <notifications@github.com> wrote:

> This PR separates the parsing and formatting of timing information as
> produced by the GNU time utility.
>
> @LabAdvComp/bioinformatics
> <https://github.com/orgs/LabAdvComp/teams/bioinformatics> thoughts?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/LabAdvComp/cdis_pipe_utils/pull/4
> Commit Summary
>
>    - separates parsing and formatting of timing info
>
> File Changes
>
>    - *M* cdis_pipe_utils/time_util.py
>    <https://github.com/LabAdvComp/cdis_pipe_utils/pull/4/files#diff-0>
>    (31)
>
> Patch Links:
>
>    - https://github.com/LabAdvComp/cdis_pipe_utils/pull/4.patch
>    - https://github.com/LabAdvComp/cdis_pipe_utils/pull/4.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LabAdvComp/cdis_pipe_utils/pull/4>.
>



-- 
*Stuti Agrawal*

**Comment by MurphyMarkW** [comment]
Awesome, thanks for checking!

**Comment by Shenglai** [comment]
Tested https://git@github.com/LabAdvComp/cdis_pipe_utils.git@f02346d580ba4e2828d5dc2074196b3cd823b87f#egg=cdis_pipe_utils with MuSE pipeline. It worked without errors.
https://github.com/NCI-GDC/muse-tool/blob/master/muse-tool/tools/muse_call.py#L18

**Comment by MurphyMarkW** [comment]
Awesomesauce, thanks!

**Pull request merged**
